---
- name: Deploy vhost & php conf
  hosts: '{{ hosts_var }}'
  vars_files:
    - ../vars/vars.yml
  gather_facts: True

  tasks:
    - name: Git Clone Repo Configs in tmp dir
      local_action: git repo=https://git.banzaimedia.it/sistemi/configs.git  dest=../tmp/configs

    - name: Backup conf etc prod and reload services
      #shell: /bin/cp -ra /etc /etc_bkp
      command: /bin/cp -ra /etc /etc_bkp

    - name: Deploy configs Farm Prod in etc
      synchronize: src={{ repo_dir }}/{{ farm }} dest=/etc/
